# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 06:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artiID', models.CharField(max_length=5, unique=True)),
                ('artiName', models.CharField(max_length=200)),
                ('artiText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentID', models.CharField(max_length=5, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 6, 27, 6, 39, 25, 351131, tzinfo=utc))),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mantra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantraID', models.CharField(max_length=5, unique=True)),
                ('mantraName', models.CharField(max_length=200)),
                ('mantraText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('updates', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('religionID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('religionName', models.CharField(max_length=200)),
                ('religionHistory', models.TextField(default='No Content')),
            ],
        ),
        migrations.AddField(
            model_name='mantra',
            name='religionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Religion'),
        ),
        migrations.AddField(
            model_name='arti',
            name='religionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Religion'),
        ),
        migrations.AlterUniqueTogether(
            name='mantra',
            unique_together=set([('religionID', 'mantraID')]),
        ),
        migrations.AlterUniqueTogether(
            name='arti',
            unique_together=set([('religionID', 'artiID')]),
        ),
    ]
