# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 27, 6, 45, 25, 559418, tzinfo=utc)),
        ),
    ]
