# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import text.models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0006_delete_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 6, 27, 8, 27, 8, 142885, tzinfo=utc))),
                ('count', models.PositiveIntegerField(default=0)),
                ('contentID', models.ForeignKey(on_delete=text.models.Arti, to='text.Mantra')),
            ],
        ),
    ]
